### ISSUE TITLE
Sugerencia: Cambiar a una versión LTS de Java (preferentemente 17)

### ISSUE THREAD

**Issue by starg09** [algo3-unsam/proyecto-base-tp#1]
Esto aplica a otros proyectos de la organización, que pueden ir acomodándose de a poco. Creo que podría ser beneficioso para los alumnos, para no depender de instalar una versión poco utilizada (y en algunas variantes de JDK, difícil de obtener), si se cambiara a una de las versiones LTS:

1. Retrotraer a JDK 11
2. Actualizar a JDK 17

Personalmente iría con la segunda opción, más que nada por un par de features que pueden haberse utilizado en algunos proyectos de algo2, o simplemente se encuentren online y fueron incluidas posterior a la versión 11, pero previo a la 14 ([fuente](https://www.marcobehler.com/guides/a-guide-to-java-versions-and-features#_java_features_8_19)):

* Nueva sintaxis de switch statements: Pueden devolver un valor, y pueden escribirse con expresiones lambda.
* Multiline strings (`"""de este estilo"""`)
* Record classes
* Descripción más detallada sobre NullPointerExceptions.
* Recuerdo en su momento comentarios positivos en algunas comunidades respecto al nuevo garbage collector de JDK 14, aunque es puramente un tema de performance (igual, es algo que puede afectar positivamente a algún alumno con un equipo más modesto)

Y algunas cosas que se agregan después de JDK 14 en 17:
* Sealed classes (clase abstracta publica, pero restringe cuales son las clases que la pueden extender)
* Pattern matching en switch statements (está en "Preview" en 17, [sigue igual en 19](https://www.happycoders.eu/java/java-19-features/#Pattern_Matching_for_switch_Third_Preview) pero no deberia recibir cambios mayores): Se pueden pasar objetos a un switch y hacer cases según su tipo.
* Foreign Function & Memory API (en "Incubator" en 17 y [en "Preview" en 19](https://www.happycoders.eu/java/java-19-features/#Foreign_Function_Memory_API_Preview)): En principio no creo que sea aplicable a nada de lo dado en la materia, pero es una API para llamar funciones y acceder a memoria afuera de la JVM.

Creo que sería un buen momento (tal vez post cursada) de actualizar los repos a 17, siendo que debería seguir siendo soportado a largo plazo como 8 y 11 en el pasado, y la próxima versión LTS recién saldría (en teoría) en Septiembre 2023 (JDK 21). Puedo ponerme poco a poco a revisar en una rama aparte y testear la actualización, que no surjan errores a raíz de la misma, y eventuales actualizaciones adicionales que puedan hacer falta (por ej.: gradle)

**Comment by fdodino** [comment]
@starg09 cierro el issue porque ya subimos a la versión 17

**Comment by starg09** [comment]
Joya! En 6 meses abro uno nuevo para 21 😂
